- name: "Table_segment"
  require_surface: false
  parent_frame_id: "base_link"
  child_frame_id: "camera_link"
  bounding_frame_id: "base_link"
  segmentation_frame_id: "base_link"
  z_min: 0.7
  z_max: 0.9
  x_min: -0.5
  x_max: 0.5
  y_min: -1.0
  y_max: -0.6
# - name: "Table_segment"
#   require_surface: false
#   parent_frame_id: "base_link"
#   child_frame_id: "camera_link"
#   bounding_frame_id: "base_link"
#   segmentation_frame_id: "base_link"
#   z_min: 0.7
#   z_max: 0.8
#   y_min: -0.5
#   y_max: 0.5
#   x_min: 0.5
#   x_max: 3
# - name: "Default Zone"
#   remove_surface: true
#   parent_frame_id: "base_link"
#   child_frame_id: "head_camera_link"
#   bounding_frame_id: "base_link"
#   segmentation_frame_id: "base_link"
#   z_min: 0.10
#   x_max: 0.8
